# **Fundamentos de Python 🐍**

Introducción a Python
- Lenguaje de programación interpretado, de alto nivel y gratuito.

Sintaxis básica

In [3]:
# Imprimir hola mundo
print('Hola Mundo')

Hola Mundo


Tipos de datos

In [4]:
# Tipos de datos
# int -> numeros enteros -> 1, 2, 3, 4, 0, -1, -2 -3, -4, -5
print(0)

0


In [6]:
print(1, 0, -1, -2, -10, 4, 3, 2, 7) # integer -> entero

1 0 -1 -2 -10 4 3 2 7


In [7]:
# Reconocer el tipo de dato
type(-1)

int

In [8]:
# float -> numero decimales -> 3.0, 4.5,(0.5 -> .5), (5.0 -> 5.)
print(.5)

0.5


In [9]:
print(5.)

5.0


In [10]:
print(-5.3)

-5.3


In [11]:
print(0.0)

0.0


In [12]:
type(0.0)

float

In [13]:
type(.5)

float

In [14]:
# str(string) -> cadena -> cadenas de texto
print('3')

3


In [15]:
type('3')

str

In [16]:
'3' + 3

TypeError: can only concatenate str (not "int") to str

In [17]:
print('Hola, mi nombre es Python')

Hola, mi nombre es Python


In [18]:
print('Tengo 20 años')

Tengo 20 años


In [26]:
print("Hola, mi nombre es Python")

Hola, mi nombre es Python


In [25]:
# bool -> Algebra George Boole
print(True) # Representación numérica es 1

True


In [24]:
print(False) # Representación numérica es 0

False


In [21]:
True + 1

2

In [23]:
False + 1

1

Variables

In [31]:
# Asignar tu primera variable
nombre = 'Yoshio'
edad = 24
pi = 3.14156
es_estudiante = True
altura = 1.75
peso = 72.6

In [32]:
print(nombre)

Yoshio


In [33]:
print(edad, pi, es_estudiante)

24 3.14156 True


In [36]:
# Listas: estructura de datos mutables
lista_mercado = ['manzana', 'avena', 'agua', 'galleta', 'papa']
print(lista_mercado)

['manzana', 'avena', 'agua', 'galleta', 'papa']


In [37]:
# Metodos
lista_mercado.append('pera')
print(lista_mercado)

['manzana', 'avena', 'agua', 'galleta', 'papa', 'pera']


In [38]:
# Eliminar un dato
lista_mercado.remove('manzana')
print(lista_mercado)

['avena', 'agua', 'galleta', 'papa', 'pera']


In [40]:
# Tuplas: estructura de datos inmutables
# (n° de transaccion, pagado/abonado)
transacciones = ((1, 345), (2, -243), 
                 (3, 54), (4, -27))
print(transacciones)

((1, 345), (2, -243), (3, 54), (4, -27))


In [54]:
# Indexación - extraer un elemento
segundo_pago = transacciones[1][1]
print('El segundo pago es:', segundo_pago)

El segundo pago es: -243


In [50]:
# Slicing - extraer un subconjunto
transacciones[0:3]

((1, 345), (2, -243), (3, 54))

In [51]:
transacciones[:3]

((1, 345), (2, -243), (3, 54))

In [52]:
transacciones[-2:]

((3, 54), (4, -27))

In [53]:
transacciones[-3:]

((2, -243), (3, 54), (4, -27))

Caso real con la librería de Numpy

In [62]:
# Importación de la librería de Numpy
import numpy as np

matriz33 = np.array([[5, 6, 4],
                    [4, 9, 3],
                    [5, 1, 0]])
matriz33

array([[5, 6, 4],
       [4, 9, 3],
       [5, 1, 0]])

In [63]:
matriz33.shape

(3, 3)

In [64]:
# Indexación
matriz33[0][1]

np.int64(6)

In [69]:
# Slicing
matriz33[:2, :2]

array([[5, 6],
       [4, 9]])

In [70]:
matriz33[-2:, -2:]

array([[9, 3],
       [1, 0]])

In [71]:
matriz33[::2, -2:]

array([[6, 4],
       [1, 0]])

Operadores aritméticos

In [80]:
a = 10
b = 5

a + b # suma

15

In [81]:
a - b # resta

5

In [82]:
a * b # multiplicacion

50

In [76]:
a / b # division

2.0

In [79]:
a ** b # potencia

100000

Operadores relacionales

In [88]:
5 == 5 # 5 es Igual que 5

True

In [87]:
10 != 6 # 10 es Diferente que 6

True

In [86]:
5 > 10 # 5 es mayor que 10

False

In [89]:
3 >= 3 # 3 es mayor o igual que 3

True

In [90]:
4 <= 5 # 4 es menor o igual que 5

True

In [94]:
# Si eres mayor de edad
edad = 23

condicion = edad > 18
print('Es mayor de edad:', condicion)

Es mayor de edad: True


Condicionales

In [97]:
# Sintaxis basica
if (edad > 18):
    print('Es mayor de edad')

Es mayor de edad


In [101]:
edad = 12
if (edad > 18):
    print('Es mayor de edad')
else:
    print('Es menor de edad')

Es menor de edad
